name: Deploy Alternativo Direct

on:
  push:
    branches:
      - main # Altere para 'master' se for o nome da sua branch

permissions:
  contents: read
  pages: write
  id-token: write

# MUDANÇA CHAVE: Nome de grupo novo para ignorar os jobs travados da fila 'pages'
concurrency:
  group: 'deploy-direto-furafila'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Pages
        uses: actions/configure-pages@v5

      - name: Upload dos arquivos
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
